sequenceDiagram
    actor Auteur
    Auteur ->> Système: Accède à la création d'article
    Système ->> Auteur: Affiche le formulaire de rédaction
    Auteur ->> Système: Remplit le formulaire et enregistrer
    Système ->> Auteur: Sauvegarde l'article et redirige l'auteur vers la liste