usecase-beta
direction LR
actor Admin("Admin")
actor Auteur("Auteur")
actor Visiteur("Visiteur")
systemBoundary "Order system"
  Consulter("Consulter les catégories")
  Ajouter("Ajouter une catégorie")
  Modifier("Modifier une catégorie")
  Supprimer("Supprimer une catégorie")
  Creer("Créer un auteur")
  Valider("Valider un article")
  Publier("Publier un article")
  Add("Ajouter un article")
  Update("Modifier un article non publié")
  Remove("Supprimer un article non publié")
  Changer("Changer son profil")
  Reinitialiser("Réinitialiser son mot de passe")
  Consul("Consulter les articles")
end
Admin --> Consulter
Admin --> Ajouter
Admin --> Modifier
Admin --> Supprimer
Admin --> Creer
Admin --> Valider
Admin --> Publier
Auteur --> Add
Auteur --> Update
Auteur --> Remove
Auteur --> Changer
Auteur --> Reinitialiser
Visiteur --> Consul